version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: finance_tracker_db
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: financeTracker
      MYSQL_USER: testUser
      MYSQL_PASSWORD: 11111
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: finance_tracker_app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3307/financeTracker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: test
    depends_on:
      - db
    restart: always



volumes:
  db_data:

